### ISSUE TITLE
The interface does not work

### ISSUE THREAD

**Issue by zombie241088** [albertnis/ld2410-configurator#1]
It doesn't work for me.
I connected LD2410C and all data is missing. I attached a screenshot.
![LD2410C](https://github.com/albertnis/ld2410-configurator/assets/56452418/9af980af-da43-4438-b91f-5ec997984294)
Also attached are the wire connections.
![IMG_20230919_223205](https://github.com/albertnis/ld2410-configurator/assets/56452418/f03820d4-5999-4f6f-af34-bf539706794e)
![IMG_20230919_223142](https://github.com/albertnis/ld2410-configurator/assets/56452418/8b18b993-6cc2-4d3f-ae80-90319a28d15a)
There is a problem or I'm doing something wrong?

**Comment by albertnis** [comment]
Thank you for this report. It’s helpful to see the photos and screenshot.
I’ll try to troubleshoot this a bit in the next couple of days.

The blue data in the console is data being sent from the configurator. No
data is being seen from your LD2410C as that would appear as white output
in the console. However, the serial connection is likely open given that
you’re past the connection screen.

- You’re using a CP2102 serial adapter, right? I think those are the
characters I see when I zoom into the photo.
- Any useful errors in the browser console?
- Have you changed the baud rate from the default on your LD2410C or in the
configurator?
- Do you see data being read from your LD2410C in a standard serial monitor
like putty or `screen`?

**Comment by albertnis** [comment]
I just noticed your wiring is a bit off. Try connecting TX to RX, RX to TX,
GND to GND and 3.3V to VCC.

**Comment by zombie241088** [comment]
> The blue data in the console is data being sent from the configurator. No data is being seen from your LD2410C as that would appear as white output in the console. However, the serial connection is likely open given that you’re past the connection screen.

I didn't understand what you wrote.


> - You’re using a CP2102 serial adapter, right? I think those are the characters I see when I zoom into the photo.

Yes


>  - Any useful errors in the browser console?

No


> - Have you changed the baud rate from the default on your LD2410C or in the
configurator?

No. Use the default.


> - Do you see data being read from your LD2410C in a standard serial monitor
like putty or `screen`?

Didn't check somewhere else but it working Home Assistant.


> I just noticed your wiring is a bit off. Try connecting TX to RX, RX to TX,
GND to GND and 3.3V to VCC.

I connted as you sussested but I to 5v intesd 3.3v. Are you sure it is the right one? In the info about this board, I see that it needs 5v power.

**Comment by albertnis** [comment]
> In the info about this board, I see that it needs 5v power. 

All good. Ignore my advice about 3V3 in this case. Can you please try the connections as per the following table and let me know if it starts working?

CP2102 | LD2410C
--- | ---
+5V | VCC
GND | GND
TX | RX
RX | TX

Before I dig into troubleshooting I want to make sure you've got everything connected correctly, as in your photos you appear to have some wires connected in the wrong places (voltage is reversed, for example).

**Comment by zombie241088** [comment]
I am updating that the problem was mine. You are right and I really connected the 5V and ground in reverse. I was sure I connected correctly. Stupid me.

Anyway, it didn't work even after I connected all the connections correctly. Now the board also stopped working in HA. In my opinion, probably as a result of the reverse connection it burned the chip.
 
So I tested with another board I have and now it works really well so you don't have to fix anything. Thanks for your help and work!

BTW, could you still explain or give a guide on what everything in the settings does so I know how to set things up correctly? Right now I can't understand anything.
![LD2410Cn](https://github.com/albertnis/ld2410-configurator/assets/56452418/83a234f2-67b0-4659-8d01-01d83596f972)

**Comment by albertnis** [comment]
That's great to hear you got it working! 

> could you still explain or give a guide on what everything in the settings does so I know how to set things up correctly? Right now I can't understand anything.

The language in the configurator interface is largely taken from the official HiLink datasheet. There is an English version of the PDF floating around that you can find in the usual ways (Google etc.). Some of the explanations aren't very helpful in there, but it's the official source and might help to explain things. The hex codes that appear in the app's console should correspond to messages documented in the PDF. White messages are being received _from_ the LD2410, and blue messages are being sent _to_ the LD2410. Beyond that, I'll point you to the official datasheet rather than giving an explanation in this issue.

That said, I've opened #2 to add some more help info in the app, because I agree it would be nice to have things explained! When I have a bit more breathing room to prioritise this project I'll take a look at it.
